services:
    app:
        image: php:8.2-fpm
        container_name: laravel-app
        user: "${UID:-1000}:${GID:-1000}"
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www

    web:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    mysql-data:
